version: "3.9"
services:
  client:
    build:
      context: client
#      args:
#        API_URL: http://localhost:8080
    image: cosuno-client
    restart: always
    ports:
      - "3000:80"
  server:
    build:
      context: server
    image: cosuno-server
    ports:
      - "8080:8080"
    restart: always